 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import ConnectDB_Notify.ChiaseDuLieu;
import ConnectDB_Notify.KetNoiDatabase;
import ConnectDB_Notify.KiemTraDuLieu;
import ConnectDB_Notify.ThongBao;
import Model.HoaDon;

import Model.SanPham;
import Process.prBanHang;
import Process.prSanPham;
import Process.prKhachHang;
import Process.prPhieuBaoHanh;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import View.ReportViewer;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import net.sourceforge.barbecue.BarcodeException;

/**
 *
 * @author ASUS
 */
public class QuanLyBanHang extends javax.swing.JPanel {
    private GiaoDienChinh parentForm;
    private DefaultTableModel tblModel1,tblModel2;
    ArrayList<String> listmaKhachHang = null;
    ArrayList<String> listmaPhieuBaoHanh = null;
    
    /**
     * Creates new form QuanLyBanHang
     */
    public QuanLyBanHang() {
        initComponents();
        
        initTable();
        
        loadDataToTable();
        
        initHoaDon();
        
        setListKhachHang();
        
        setListPhieuBaoHanh();
    }
    
    private String getsoHD(){
        int count =0;
        prBanHang kt = new prBanHang();
        try {
            count = kt.soHD();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(count<9){
            return "HD" + 00 +(count+1);
        }else if(count>=9 && count<99){
            return "HD" + 0 +(count+1);
        }else
            return "HD"  +(count+1);
    }
    
     private void initTable(){
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(new String[]{"Mã sản phẩm","Tên sản phẩm","Màu sắc","Giá bán","Số lượng"});
        tableSP.setModel(tblModel1);
        tblModel2 = new DefaultTableModel();
        tblModel2.setColumnIdentifiers(new String[]{"Mã sản phẩm","Tên sản phẩm","Giá bán","Số lượng"});
        tableHD.setModel(tblModel2);
    }
     
    private void initHoaDon(){
        txtngayLapHD.setText(java.time.LocalDate.now().toString());
        txtmaNV.setText(ChiaseDuLieu.nguoiDangnhap.getMaNV());
        txtsoHD.setText(getsoHD());
    }
    
    private void loadDataToTable(){
        try{
            prSanPham kt = new prSanPham();
            List<SanPham> list = kt.FindAll();
            tblModel1.setRowCount(0);
            tblModel2.setRowCount(0);
            for(SanPham it :list){
                tblModel1.addRow(new Object[]{
                it.getMaSP(), it.getTenSP(), it.getMauSac(), it.getDongia(), it.getSoluong()
                });
            }
            tblModel1.fireTableDataChanged();
            txttongTien.setText("0");
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableHD = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txttongTien = new javax.swing.JTextField();
        btnthanhToan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtngayLapHD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsoHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbmaKH = new javax.swing.JComboBox<>();
        cbmaPBH = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản Lý Bán Hàng");

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HÓA ĐƠN THANH TOÁN");

        tableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableHD);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tổng tiền:");

        txttongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttongTien.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttongTien.setToolTipText("");
        txttongTien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnthanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthanhToan.setText("Thanh toán");
        btnthanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhToanActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày HD:");
        jLabel2.setToolTipText("");

        jLabel4.setText("Số HD:");

        jLabel5.setText("Mã NV:");

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã KH:");

        jLabel8.setText("Mã PBH:");

        cbmaKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbmaPBH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthanhToan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtngayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbmaPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtsoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsoHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngayLapHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(cbmaPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txttongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthanhToan)
                    .addComponent(btnRefresh))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSP);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BẢNG SẢN PHẨM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDataToTable();
        txtsoHD.setText(getsoHD());
    }//GEN-LAST:event_btnRefreshActionPerformed

    
    private void tableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHDMouseClicked
        int numrow = tableHD.getRowCount();
        double tongTien =0;
        for( int i =0;i <numrow; i++){
            double gia= Double.valueOf(tableHD.getValueAt(i,2).toString());
            double sl = Double.valueOf(tableHD.getValueAt(i,3).toString());
            tongTien+=(gia*sl);
        }
        txttongTien.setText(Long.toString((long)tongTien));
    }//GEN-LAST:event_tableHDMouseClicked

    private void tableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPMouseClicked
        int index = tableSP.getSelectedRow();
        if(index< tableSP.getRowCount()&&index>=0){
            String row[]= new String[4];
            row[0] = tableSP.getValueAt(index, 0).toString();
            row[1] = tableSP.getValueAt(index, 1).toString();
            row[2] = tableSP.getValueAt(index, 3).toString();
            row[3] ="1";
            tblModel2.addRow(row);
        }
        int numrow = tableHD.getRowCount();
        double tongTien =0;
        for( int i =0;i <numrow; i++){
            double gia= Double.valueOf(tableHD.getValueAt(i,2).toString());
            double sl = Double.valueOf(tableHD.getValueAt(i,3).toString());
            tongTien+=(gia*sl);
        }
        txttongTien.setText(Long.toString((long)tongTien));
    }//GEN-LAST:event_tableSPMouseClicked

    private void btnthanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhToanActionPerformed
        int numrow = tableHD.getRowCount();
        HoaDon hd =new HoaDon();
        if(ThongBao.showXacNhan(parentForm, "Xác nhận thanh toán", "Hỏi")== JOptionPane.NO_OPTION){
                return;
        }
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtsoHD, sb, "Số hóa đơn trống!!");
        int countResult=0;
        String soHD = txtsoHD.getText();
        String maNV = txtmaNV.getText();
        String maKH = cbmaKH.getSelectedItem().toString();
        String maPBH = cbmaPBH.getSelectedItem().toString();
        
        Long tongTien= Long.parseLong(txttongTien.getText());
        SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try{
            java.util.Date ngayLapHD =DateFormat.parse(txtngayLapHD.getText());
            prBanHang kt = new prBanHang();
            countResult=kt.insert_HD(soHD, maKH, maPBH, maNV, ngayLapHD, tongTien);
        }
        catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình lưu", 
                    "Sai ngày định dạng",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(QuanLyBaoHanh.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            hd.setSoHD(txtsoHD.getText());
            prBanHang kt =new prBanHang();
                for( int i =0;i <numrow; i++){
                hd.setMaSP(tableHD.getValueAt(i,0).toString());
                hd.setSoluong(Long.valueOf(tableHD.getValueAt(i, 3).toString()));
                if(kt.insert_CTHD(hd));
               }
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
        if(countResult==1){
            XuatHoaDon(hd.getSoHD());
        }
        
        txttongTien.setText("0");
        loadDataToTable();
        txtsoHD.setText(getsoHD());
    }//GEN-LAST:event_btnthanhToanActionPerformed
    
    private void setListKhachHang(){
        prKhachHang kt = new prKhachHang();
        HashMap<String, String> listKhachHang = kt.getListKhachHang();
        listmaKhachHang = new ArrayList<String>();
        listmaKhachHang.addAll(listKhachHang.keySet());
        ArrayList<String> listMaKH = new ArrayList<String>();
        listMaKH.addAll(listKhachHang.values());
        cbmaKH.setModel(new DefaultComboBoxModel(listMaKH.toArray()));
    }
    
    private void setListPhieuBaoHanh(){
        prPhieuBaoHanh kt = new prPhieuBaoHanh();
        HashMap<String, String> listPhieuBaoHanh = kt.getListPhieuBaoHanh();
        listmaPhieuBaoHanh = new ArrayList<String>();
        listmaPhieuBaoHanh.addAll(listPhieuBaoHanh.keySet());
        ArrayList<String> listMaPBH = new ArrayList<String>();
        listMaPBH.addAll(listPhieuBaoHanh.values());
        cbmaPBH.setModel(new DefaultComboBoxModel(listMaPBH.toArray()));
    }
    
    // Hàm xuất hóa đơn
    public void XuatHoaDon(String sohd){
        try{
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src//Resource//reportHoaDon.jrxml");
            
            map.put("SoHD", sohd);
            
            JasperPrint p = JasperFillManager.fillReport(report, map, KetNoiDatabase.getOracleConnection());
            
            JasperViewer.viewReport(p, false);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnthanhToan;
    private javax.swing.JComboBox<String> cbmaKH;
    private javax.swing.JComboBox<String> cbmaPBH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableHD;
    private javax.swing.JTable tableSP;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtngayLapHD;
    private javax.swing.JTextField txtsoHD;
    private javax.swing.JTextField txttongTien;
    // End of variables declaration//GEN-END:variables
}
