/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import ConnectDB_Notify.KiemTraDuLieu;
import ConnectDB_Notify.ThongBao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Process.prPhieuBaoHanh;
import Model.PhieuBaoHanh;
import Model.BaoHanhSP;
import Process.prBaoHanhSP;
import Process.prSanPham;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ASUS
 */
public class QuanLyBaoHanh extends javax.swing.JPanel {
    private GiaoDienChinh parentForm;
    private DefaultTableModel tblModel1, tblModel2;
    
     ArrayList<String> listmaSP = null;
    /**
     * Creates new form QuanLyBaoHanh
     */
    public QuanLyBaoHanh() {
        initComponents();
        
        initTable();
        
        loadDataToTable();
        
        setListMaSP();
    }
    
    
    
    private void initTable(){
        tblModel1 = new DefaultTableModel();
        tblModel2 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(new String[]{"Mã phiếu bảo hành","Ngày bắt đầu","Ngày hết hạn"});
        tablePhieuBaoHanh.setModel(tblModel1);
        tblModel2.setColumnIdentifiers(new String[] {"Mã bảo hành","Mã sản phẩm", "Ngày bảo hành","Chi phí bảo hành","Mô tả lỗi"});
        tableBHSP.setModel(tblModel2);
    }
    
    private void loadDataToTable(){
        try{
            prPhieuBaoHanh kt1 = new prPhieuBaoHanh();
            prBaoHanhSP kt2 = new prBaoHanhSP();
            
            List<PhieuBaoHanh> list1 = kt1.FindAll();
            List<BaoHanhSP> list2 = kt2.FindAll();
            tblModel1.setRowCount(0);
            for(PhieuBaoHanh it :list1){
                tblModel1.addRow(new Object[]{
                it.getMaPBH(), it.getNgaybatdau(),it.getNgayhethan(), 
                });
            }
            tblModel1.fireTableDataChanged();
            tblModel2.setRowCount(0);
            for(BaoHanhSP it :list2){
                tblModel2.addRow(new Object[]{
                it.getMaBH(), it.getMaSP(),it.getNgayBH(), it.getChiphi(),it.getMotaLoi()
                });
            }
            tblModel2.fireTableDataChanged();
            
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }
    
    private String getmaBH(){
        int count =0;
        prBaoHanhSP kt = new prBaoHanhSP();
        try {
            count = kt.somaBH();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(count<9){
            return "BH00" +(count+1);
        }else if(count>=9 && count<99){
            return "BH" + 0 +(count+1);
        }else
            return "BH"  +(count+1);
    }
    
    private String getmaPBH(){
        int count =0;
        prPhieuBaoHanh kt = new prPhieuBaoHanh();
        try {
            count = kt.somaPBH();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(count<9){
            return "PBH" + 0 +(count+1);
        } else if(count>9 && count<99)
            return "PBH" +(count+1);
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtmaBH = new javax.swing.JTextField();
        txtchiphiBH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmotaLoi = new javax.swing.JTextArea();
        btnthemBH = new javax.swing.JButton();
        btnxoaBH = new javax.swing.JButton();
        btncapnhatBH = new javax.swing.JButton();
        btnluuBH = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtmaBH1 = new javax.swing.JTextField();
        btntracuuBH = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBHSP = new javax.swing.JTable();
        dateBH = new com.toedter.calendar.JDateChooser();
        cbmaSP = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThemPBH = new javax.swing.JButton();
        btnXoaPBH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCapnhatPBH = new javax.swing.JButton();
        btnLuuPBH = new javax.swing.JButton();
        btnTracuuPBH = new javax.swing.JButton();
        txtMaPBH1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhieuBaoHanh = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtMaPBH = new javax.swing.JTextField();
        dateBD = new com.toedter.calendar.JDateChooser();
        dateHH = new com.toedter.calendar.JDateChooser();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Bảo hành sản phẩm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("THÔNG TIN BẢO HÀNH");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Mã bảo hành:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Mã sản phẩm:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Ngày bảo hành:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mô tả lỗi:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Chi phí bảo hành:");

        txtmaBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtchiphiBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtmotaLoi.setColumns(20);
        txtmotaLoi.setRows(5);
        jScrollPane2.setViewportView(txtmotaLoi);

        btnthemBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnthemBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/add.png"))); // NOI18N
        btnthemBH.setText("Thêm mới");
        btnthemBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemBHActionPerformed(evt);
            }
        });

        btnxoaBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnxoaBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/delete.png"))); // NOI18N
        btnxoaBH.setText("Xóa");
        btnxoaBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaBHActionPerformed(evt);
            }
        });

        btncapnhatBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncapnhatBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/update.png"))); // NOI18N
        btncapnhatBH.setText("Cập nhật");
        btncapnhatBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatBHActionPerformed(evt);
            }
        });

        btnluuBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnluuBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/save.png"))); // NOI18N
        btnluuBH.setText("Lưu");
        btnluuBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuBHActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Mã bảo hành:");

        txtmaBH1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmaBH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaBH1ActionPerformed(evt);
            }
        });

        btntracuuBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btntracuuBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        btntracuuBH.setText("Tra cứu");
        btntracuuBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntracuuBHActionPerformed(evt);
            }
        });

        tableBHSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBHSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBHSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBHSP);

        dateBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbmaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbmaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtmaBH1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntracuuBH)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btncapnhatBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnluuBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnthemBH)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnxoaBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaBH)
                            .addComponent(dateBH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtchiphiBH)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtmaBH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btntracuuBH))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtmaBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(dateBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtchiphiBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthemBH)
                            .addComponent(btnxoaBH))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnluuBH)
                            .addComponent(btncapnhatBH))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bảo hành sản phẩm", jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Phiếu Bảo Hành");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("THÔNG TIN PHIẾU BẢO HÀNH");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã phiếu bảo hành:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày bắt đầu:");

        btnThemPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/add.png"))); // NOI18N
        btnThemPBH.setText("Thêm mới");
        btnThemPBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPBHActionPerformed(evt);
            }
        });

        btnXoaPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/delete.png"))); // NOI18N
        btnXoaPBH.setText("Xóa");
        btnXoaPBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPBHActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày hết hạn:");

        btnCapnhatPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapnhatPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/update.png"))); // NOI18N
        btnCapnhatPBH.setText("Cập nhật");
        btnCapnhatPBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatPBHActionPerformed(evt);
            }
        });

        btnLuuPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuuPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/save.png"))); // NOI18N
        btnLuuPBH.setText("Lưu");
        btnLuuPBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPBHActionPerformed(evt);
            }
        });

        btnTracuuPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTracuuPBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N
        btnTracuuPBH.setText("Tra cứu");
        btnTracuuPBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTracuuPBHActionPerformed(evt);
            }
        });

        txtMaPBH1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Mã phiếu bảo hành:");

        tablePhieuBaoHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePhieuBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhieuBaoHanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePhieuBaoHanh);

        txtMaPBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dateBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dateHH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtMaPBH1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTracuuPBH)
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(btnThemPBH)
                    .addComponent(btnCapnhatPBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXoaPBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuuPBH, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaPBH, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(dateBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateHH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel1)
                    .addContainerGap(857, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPBH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTracuuPBH)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dateBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dateHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemPBH)
                            .addComponent(btnLuuPBH))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaPBH)
                            .addComponent(btnCapnhatPBH))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Phiếu bảo hành", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaPBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtMaPBH, sb, "Mã phiếu bảo hành trống!!");
        if(sb.length()>0){
            ThongBao.showLoi(parentForm, sb.toString(), "Lỗi!!");
            return;
        }
        if(ThongBao.showXacNhan(parentForm, "Bạn có muốn xóa phiếu bảo hành này không?", "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }
        try{
            prPhieuBaoHanh kt = new prPhieuBaoHanh();
            if(kt.delete(txtMaPBH.getText())){
                ThongBao.showThongBao(parentForm, "Phiếu bảo hành đã được xóa", "Thông báo");
                btnThemPBHActionPerformed(evt);
                loadDataToTable();
            }else{
                ThongBao.showXacNhan(parentForm, "Lỗi!! Không thể xóa.", "Cảnh báo");
            }
            
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaPBHActionPerformed

    private void btnThemPBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPBHActionPerformed
        Date date=java.util.Calendar.getInstance().getTime(); 
        txtMaPBH.setText(getmaPBH());
        dateBD.setDate(date);
        dateHH.setDate(null);
        loadDataToTable();
    }//GEN-LAST:event_btnThemPBHActionPerformed

    private void btnCapnhatPBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatPBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtMaPBH, sb, "Mã phiếu bảo hành trống!!");
        int countResult=0;
        String maPBHText = txtMaPBH.getText();
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MMM-yy");
        String NgayBDdate =DateFormat.format(dateBD.getDate());
        String NgayHHdate = DateFormat.format(dateHH.getDate());
        prPhieuBaoHanh kt = new prPhieuBaoHanh();
        countResult= kt.update(maPBHText, NgayBDdate, NgayHHdate);
    
        if(countResult == 0){
             JOptionPane.showMessageDialog(this,"Cập nhật không thành công!", "Lỗi cập nhật CSDL",JOptionPane.ERROR_MESSAGE);
        }else if(countResult==1){
            JOptionPane.showMessageDialog(this,"Cập nhật thành thành công!");
            loadDataToTable();
        }
    }//GEN-LAST:event_btnCapnhatPBHActionPerformed

    private void btnLuuPBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtMaPBH, sb, "Mã phiếu bảo hành trống!!");
        int countResult=0;
        String maPBHText = txtMaPBH.getText();
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MMM-yy");
        String NgayBDdate =DateFormat.format(dateBD.getDate());
        String NgayHHdate = DateFormat.format(dateHH.getDate());
        prPhieuBaoHanh kt = new prPhieuBaoHanh();
        countResult= kt.insert(maPBHText, NgayBDdate, NgayHHdate);
    
        if(countResult == 0){
             JOptionPane.showMessageDialog(this,"Lưu không thành công!", "Lỗi thêm CSDL",JOptionPane.ERROR_MESSAGE);
        }else if(countResult==1){
            JOptionPane.showMessageDialog(this,"Lưu thành thành công!");
            loadDataToTable();
        }
    }//GEN-LAST:event_btnLuuPBHActionPerformed

    private void btnTracuuPBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTracuuPBHActionPerformed
        try{
            prPhieuBaoHanh kt =new prPhieuBaoHanh();
            PhieuBaoHanh pbh = kt.FindByID(txtMaPBH1.getText());
            
            if(pbh != null){
                txtMaPBH.setText(pbh.getMaPBH());
                dateBD.setDate(pbh.getNgaybatdau());
                dateHH.setDate(pbh.getNgayhethan());
            }else{
                ThongBao.showThongBao(parentForm, "Không tìm thấy mã phiếu bảo hành theo yêu cầu", "Thông báo");
            }
            
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnTracuuPBHActionPerformed

    private void tablePhieuBaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePhieuBaoHanhMouseClicked
        try{
            int row = tablePhieuBaoHanh.getSelectedRow();
            
            if(row>=0){
                String id = (String) tablePhieuBaoHanh.getValueAt(row, 0);
                prPhieuBaoHanh kt = new prPhieuBaoHanh();
                PhieuBaoHanh pbh = kt.FindByID(id);
                
                if(pbh != null){
                    txtMaPBH.setText(pbh.getMaPBH());
                    dateBD.setDate(pbh.getNgaybatdau());
                    dateHH.setDate(pbh.getNgayhethan());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }                                          
    }//GEN-LAST:event_tablePhieuBaoHanhMouseClicked

    private void txtmaBH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaBH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaBH1ActionPerformed

    private void btnthemBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemBHActionPerformed
        Date date=java.util.Calendar.getInstance().getTime();  
        txtmaBH.setText(getmaBH());
        dateBH.setDate(date);
        txtchiphiBH.setText("");
        txtmotaLoi.setText("");
        loadDataToTable();
    }//GEN-LAST:event_btnthemBHActionPerformed

    private void btnxoaBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtmaBH, sb, "Mã bảo hành trống!!");
        if(sb.length()>0){
            ThongBao.showLoi(parentForm, sb.toString(), "Lỗi!!");
            return;
        }
        if(ThongBao.showXacNhan(parentForm, "Bạn có muốn xóa bảo hành này không?", "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }
        try{
            prBaoHanhSP kt = new prBaoHanhSP();
            if(kt.delete(txtmaBH.getText())){
                ThongBao.showThongBao(parentForm, "Bảo hành đã được xóa", "Thông báo");
                btnthemBHActionPerformed(evt);
                loadDataToTable();
            }else{
                ThongBao.showXacNhan(parentForm, "Lỗi!! Không thể xóa.", "Cảnh báo");
            }
            
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnxoaBHActionPerformed

    private void btncapnhatBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtmaBH, sb, "Mã bảo hành trống!!");
        int countResult=0;
        String maBHText = txtmaBH.getText();
        String maSPText = cbmaSP.getSelectedItem().toString();
        Double chiPhiText = Double.parseDouble(txtchiphiBH.getText());
        String motaLoiText = txtmotaLoi.getText();
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MMM-yy");
        String NgayBHdate =DateFormat.format(dateBH.getDate());
        prBaoHanhSP kt = new prBaoHanhSP();
        countResult= kt.update(maBHText, maSPText,NgayBHdate,chiPhiText, motaLoiText);
    
        if(countResult == 0){
             JOptionPane.showMessageDialog(this,"Cập nhật không thành công!", "Lỗi cập nhật CSDL",JOptionPane.ERROR_MESSAGE);
        }else if(countResult==1 && Double.parseDouble(txtchiphiBH.getText())>=0){
            JOptionPane.showMessageDialog(this,"Cập nhật thành thành công!");
            loadDataToTable();
        }
    }//GEN-LAST:event_btncapnhatBHActionPerformed

    private void btnluuBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuBHActionPerformed
        StringBuilder sb =new StringBuilder();
        KiemTraDuLieu.DuLieuTrong(txtmaBH, sb, "Mã  bảo hành trống!!");
        int countResult=0;
        String maBHText = txtmaBH.getText();
        String maSPText = cbmaSP.getSelectedItem().toString();
        Double chiPhiText = Double.parseDouble(txtchiphiBH.getText());
        String motaLoiText = txtmotaLoi.getText();
        SimpleDateFormat DateFormat = new SimpleDateFormat("dd-MMM-yy");
        String NgayBHdate =DateFormat.format(dateBH.getDate());
        prBaoHanhSP kt = new prBaoHanhSP();
        countResult= kt.insert(maBHText, maSPText, NgayBHdate, chiPhiText,motaLoiText);
    
        if(countResult == 0){
             JOptionPane.showMessageDialog(this,"Lưu không thành công!", "Lỗi thêm CSDL",JOptionPane.ERROR_MESSAGE);
        }else if(countResult==1 && Double.parseDouble(txtchiphiBH.getText())>=0){
            JOptionPane.showMessageDialog(this,"Lưu thành thành công!");
            loadDataToTable();
        }
    }//GEN-LAST:event_btnluuBHActionPerformed

    private void btntracuuBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntracuuBHActionPerformed
        try{
            prBaoHanhSP kt =new prBaoHanhSP();
            BaoHanhSP bh = kt.FindByID(txtmaBH1.getText());
            
            if(bh != null){
                txtmaBH.setText(bh.getMaBH());
                cbmaSP.setSelectedItem(bh.getMaSP());
                dateBH.setDate(bh.getNgayBH());
                txtchiphiBH.setText(String.format("%.0f",(double) bh.getChiphi()));
                txtmotaLoi.setText(bh.getMotaLoi());
            }else{
                ThongBao.showThongBao(parentForm, "Không tìm thấy mã thông tin bảo hành theo yêu cầu", "Thông báo");
            }
            
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btntracuuBHActionPerformed

    private void tableBHSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBHSPMouseClicked
        try{
            int row = tableBHSP.getSelectedRow();
            if(row>=0){
                String id = (String) tableBHSP.getValueAt(row, 0);
                prBaoHanhSP kt = new prBaoHanhSP();
                BaoHanhSP bh = kt.FindByID(id);
                
                if(bh != null){
                    txtmaBH.setText(bh.getMaBH());
                    cbmaSP.setSelectedItem(bh.getMaSP());
                    dateBH.setDate(bh.getNgayBH());
                    txtchiphiBH.setText(String.format("%.0f",(double) bh.getChiphi()));
                    txtmotaLoi.setText(bh.getMotaLoi());
                }
            }
        }catch(Exception e){
            e.printStackTrace();
            ThongBao.showLoi(parentForm, e.getMessage(), "Lỗi");
    }                                          
    }//GEN-LAST:event_tableBHSPMouseClicked

     private void setListMaSP(){
        prSanPham kt = new prSanPham();
        HashMap<String, String> listSanPham = kt.getlistmaSP();
        listmaSP = new ArrayList<String>();
        listmaSP.addAll(listSanPham.keySet());
        ArrayList<String> listMaSP = new ArrayList<String>();
        listMaSP.addAll(listSanPham.values());
        cbmaSP.setModel(new DefaultComboBoxModel(listMaSP.toArray()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatPBH;
    private javax.swing.JButton btnLuuPBH;
    private javax.swing.JButton btnThemPBH;
    private javax.swing.JButton btnTracuuPBH;
    private javax.swing.JButton btnXoaPBH;
    private javax.swing.JButton btncapnhatBH;
    private javax.swing.JButton btnluuBH;
    private javax.swing.JButton btnthemBH;
    private javax.swing.JButton btntracuuBH;
    private javax.swing.JButton btnxoaBH;
    private javax.swing.JComboBox<String> cbmaSP;
    private com.toedter.calendar.JDateChooser dateBD;
    private com.toedter.calendar.JDateChooser dateBH;
    private com.toedter.calendar.JDateChooser dateHH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableBHSP;
    private javax.swing.JTable tablePhieuBaoHanh;
    private javax.swing.JTextField txtMaPBH;
    private javax.swing.JTextField txtMaPBH1;
    private javax.swing.JTextField txtchiphiBH;
    private javax.swing.JTextField txtmaBH;
    private javax.swing.JTextField txtmaBH1;
    private javax.swing.JTextArea txtmotaLoi;
    // End of variables declaration//GEN-END:variables
}
